### ISSUE TITLE
Large amount of directories when running ensemble of models

### ISSUE THREAD

**Issue by Daafip** [eWaterCycle/ewatercycle-leakybucket#7]
In the current setup, a config file directory is created every model instance 

https://github.com/eWaterCycle/ewatercycle-leakybucket/blob/450f8558985997446f912a826212acf00995e339/src/ewatercycle_leakybucket/model.py#L39
 
Looking at Data Assimilation, a large amount of models are run. This creates a large amoount of config files for every instance of the model (currently I have 180 folders from testing :P).

I thought of: 

```py
config_file = self._cfg_dir.parent / "HBV_models" / self._cfg_dir.name / "HBV_config.json"
```

Is the `self._cfg_dir` used elsewhere? or is this safe to implement?

**Comment by BSchilperoort** [comment]
This is intentional. You can specify where the folders end up in the ewatercycle configuration

```
                we don't create a temporary directory,
                but rather a time-stamped folder inside
                ewatercycle.CFG['output_dir'].
```
https://github.com/eWaterCycle/ewatercycle/blob/d02450bb079d213f1c7f2ac0100268b0ad8cab1b/src/ewatercycle/base/model.py#L95

I think the best way to tackle this is to modify your `.finalize` method so it cleans up the `_cfg_dir`.

For safety you can first delete the config file and then use `Path.rmdir()` which [should fail if the directory is not empty](https://docs.python.org/3/library/pathlib.html#pathlib.Path.rmdir).
